spring.application.name=chatbot
server.port=8080
openai.api.key=
camunda.bpmn.process-id=Process_xadodio_chat
zeebe.client.cloud.cluster-id=${CAMUNDA_CLUSTER_ID:be410dc2-a8a3-4122-bf93-923ca9756910}
zeebe.client.cloud.client-id=${CAMUNDA_CLIENT_ID:OU4v6uJeJazNrSqiujqyMBg6uWW.ddOV}
zeebe.client.cloud.client-secret=${CAMUNDA_CLIENT_SECRET:FaDeiIYRC3RgTKqWzXMlFQnhc0s_Nf93Bywv0rRyUK63XbwgLl48a4NgpTNj6bEZ}
zeebe.client.cloud.region=${CAMUNDA_REGION:ric-1}

# Local / self-managed (uncomment instead of zeebe.client.cloud.*)
# zeebe.client.broker.gateway-address=127.0.0.1:26500
# zeebe.client.security.plaintext=true
