spring.application.name=chatbot
server.port=8080

openai.api.key=
camunda.bpmn.process-id=Process_xadodio_chat

camunda.client.mode=saas
camunda.client.cloud.cluster-id=${CAMUNDA_CLUSTER_ID:38656985-c1af-4b5c-9324-a732861b4558}
camunda.client.cloud.region=${CAMUNDA_REGION:fra-1}
camunda.client.auth.client-id=${CAMUNDA_CLIENT_ID:ctCdjUQFvYAIxNNNStZbT8GiZnJ1SWVO}
camunda.client.auth.client-secret=${CAMUNDA_CLIENT_SECRET:1nIzdipE2yrSdQhCsE_5xS6-zoJrF6mfFi9rPsYd4uqr_uQokhS3hd57MshwUqDn}
camunda.client.prefer-rest-over-grpc=false
camunda.client.zeebe.defaults.job-timeout=PT1H

#camunda.client.prefer-rest-over-grpc=false
# Match BPMN "Stop chat after 1 hour" timer on the User_Feedback task.
#camunda.client.zeebe.defaults.job-timeout=PT1H
#camunda.client.grpc-address=${CAMUNDA_CLIENT_GRPC_ADDRESS:https://test-zeebe.naitive.ai}
#camunda.client.rest-address=${CAMUNDA_CLIENT_REST_ADDRESS:https://test-camunda.naitive.ai/orchestration}
#camunda.client.keep-alive=PT120S
#camunda.client.request-timeout=PT120S
#camunda.client.auth.method=oidc
#camunda.client.auth.client-id=${CAMUNDA_CLIENT_ID:camunda-app-integration}
#camunda.client.auth.client-secret=${CAMUNDA_CLIENT_SECRET:super-secret-123}
#camunda.client.auth.token-url=${CAMUNDA_TOKEN_URL:https://test-keycloak.naitive.ai/auth/realms/camunda-platform/protocol/openid-connect/token}
#camunda.client.auth.audience=orchestration-api
#camunda.client.zeebe.defaults.job-timeout=PT60S